# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/code/Image_Processing_Project2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/code/Image_Processing_Project2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/code/Image_Processing_Project2/CMakeFiles /home/user/code/Image_Processing_Project2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/code/Image_Processing_Project2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named txt_to_pcd

# Build rule for target.
txt_to_pcd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 txt_to_pcd
.PHONY : txt_to_pcd

# fast build rule for target.
txt_to_pcd/fast:
	$(MAKE) -f CMakeFiles/txt_to_pcd.dir/build.make CMakeFiles/txt_to_pcd.dir/build
.PHONY : txt_to_pcd/fast

#=============================================================================
# Target rules for targets named scaia_icp

# Build rule for target.
scaia_icp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scaia_icp
.PHONY : scaia_icp

# fast build rule for target.
scaia_icp/fast:
	$(MAKE) -f CMakeFiles/scaia_icp.dir/build.make CMakeFiles/scaia_icp.dir/build
.PHONY : scaia_icp/fast

#=============================================================================
# Target rules for targets named pcd_rotate_pan

# Build rule for target.
pcd_rotate_pan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pcd_rotate_pan
.PHONY : pcd_rotate_pan

# fast build rule for target.
pcd_rotate_pan/fast:
	$(MAKE) -f CMakeFiles/pcd_rotate_pan.dir/build.make CMakeFiles/pcd_rotate_pan.dir/build
.PHONY : pcd_rotate_pan/fast

#=============================================================================
# Target rules for targets named icp

# Build rule for target.
icp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 icp
.PHONY : icp

# fast build rule for target.
icp/fast:
	$(MAKE) -f CMakeFiles/icp.dir/build.make CMakeFiles/icp.dir/build
.PHONY : icp/fast

src/icp.o: src/icp.cpp.o

.PHONY : src/icp.o

# target to build an object file
src/icp.cpp.o:
	$(MAKE) -f CMakeFiles/icp.dir/build.make CMakeFiles/icp.dir/src/icp.cpp.o
.PHONY : src/icp.cpp.o

src/icp.i: src/icp.cpp.i

.PHONY : src/icp.i

# target to preprocess a source file
src/icp.cpp.i:
	$(MAKE) -f CMakeFiles/icp.dir/build.make CMakeFiles/icp.dir/src/icp.cpp.i
.PHONY : src/icp.cpp.i

src/icp.s: src/icp.cpp.s

.PHONY : src/icp.s

# target to generate assembly for a file
src/icp.cpp.s:
	$(MAKE) -f CMakeFiles/icp.dir/build.make CMakeFiles/icp.dir/src/icp.cpp.s
.PHONY : src/icp.cpp.s

src/pcd_rotate_pan.o: src/pcd_rotate_pan.cpp.o

.PHONY : src/pcd_rotate_pan.o

# target to build an object file
src/pcd_rotate_pan.cpp.o:
	$(MAKE) -f CMakeFiles/pcd_rotate_pan.dir/build.make CMakeFiles/pcd_rotate_pan.dir/src/pcd_rotate_pan.cpp.o
.PHONY : src/pcd_rotate_pan.cpp.o

src/pcd_rotate_pan.i: src/pcd_rotate_pan.cpp.i

.PHONY : src/pcd_rotate_pan.i

# target to preprocess a source file
src/pcd_rotate_pan.cpp.i:
	$(MAKE) -f CMakeFiles/pcd_rotate_pan.dir/build.make CMakeFiles/pcd_rotate_pan.dir/src/pcd_rotate_pan.cpp.i
.PHONY : src/pcd_rotate_pan.cpp.i

src/pcd_rotate_pan.s: src/pcd_rotate_pan.cpp.s

.PHONY : src/pcd_rotate_pan.s

# target to generate assembly for a file
src/pcd_rotate_pan.cpp.s:
	$(MAKE) -f CMakeFiles/pcd_rotate_pan.dir/build.make CMakeFiles/pcd_rotate_pan.dir/src/pcd_rotate_pan.cpp.s
.PHONY : src/pcd_rotate_pan.cpp.s

src/scaia_icp.o: src/scaia_icp.cpp.o

.PHONY : src/scaia_icp.o

# target to build an object file
src/scaia_icp.cpp.o:
	$(MAKE) -f CMakeFiles/scaia_icp.dir/build.make CMakeFiles/scaia_icp.dir/src/scaia_icp.cpp.o
.PHONY : src/scaia_icp.cpp.o

src/scaia_icp.i: src/scaia_icp.cpp.i

.PHONY : src/scaia_icp.i

# target to preprocess a source file
src/scaia_icp.cpp.i:
	$(MAKE) -f CMakeFiles/scaia_icp.dir/build.make CMakeFiles/scaia_icp.dir/src/scaia_icp.cpp.i
.PHONY : src/scaia_icp.cpp.i

src/scaia_icp.s: src/scaia_icp.cpp.s

.PHONY : src/scaia_icp.s

# target to generate assembly for a file
src/scaia_icp.cpp.s:
	$(MAKE) -f CMakeFiles/scaia_icp.dir/build.make CMakeFiles/scaia_icp.dir/src/scaia_icp.cpp.s
.PHONY : src/scaia_icp.cpp.s

src/txt_to_pcd.o: src/txt_to_pcd.cpp.o

.PHONY : src/txt_to_pcd.o

# target to build an object file
src/txt_to_pcd.cpp.o:
	$(MAKE) -f CMakeFiles/txt_to_pcd.dir/build.make CMakeFiles/txt_to_pcd.dir/src/txt_to_pcd.cpp.o
.PHONY : src/txt_to_pcd.cpp.o

src/txt_to_pcd.i: src/txt_to_pcd.cpp.i

.PHONY : src/txt_to_pcd.i

# target to preprocess a source file
src/txt_to_pcd.cpp.i:
	$(MAKE) -f CMakeFiles/txt_to_pcd.dir/build.make CMakeFiles/txt_to_pcd.dir/src/txt_to_pcd.cpp.i
.PHONY : src/txt_to_pcd.cpp.i

src/txt_to_pcd.s: src/txt_to_pcd.cpp.s

.PHONY : src/txt_to_pcd.s

# target to generate assembly for a file
src/txt_to_pcd.cpp.s:
	$(MAKE) -f CMakeFiles/txt_to_pcd.dir/build.make CMakeFiles/txt_to_pcd.dir/src/txt_to_pcd.cpp.s
.PHONY : src/txt_to_pcd.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... txt_to_pcd"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... scaia_icp"
	@echo "... edit_cache"
	@echo "... pcd_rotate_pan"
	@echo "... icp"
	@echo "... src/icp.o"
	@echo "... src/icp.i"
	@echo "... src/icp.s"
	@echo "... src/pcd_rotate_pan.o"
	@echo "... src/pcd_rotate_pan.i"
	@echo "... src/pcd_rotate_pan.s"
	@echo "... src/scaia_icp.o"
	@echo "... src/scaia_icp.i"
	@echo "... src/scaia_icp.s"
	@echo "... src/txt_to_pcd.o"
	@echo "... src/txt_to_pcd.i"
	@echo "... src/txt_to_pcd.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

